name: Generate JSON file listing all files in 'json' folder

on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate and commit JSON file
        run: |
          echo '{
            "files": [
              $(ls json)
            ]
          }' > json_index.json
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add json_index.json
          git commit -m "Generate JSON file listing all files in 'json' folder"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
