name: Generate JSON file listing all files in 'json' folder

on:
  push:
    branches:
      - main

jobs:
  generate_json:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate JSON file
        run: |
          files=$(ls json | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo '{
            "files": '"$files"'
          }' > json_index.json

      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit changes
        run: |
          git add json_index.json
          git commit -m "Generate JSON file listing all files in 'json' folder"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
