name: Update JSON Index - file listing all files in 'json' folder

on:
  push:
    paths:
      - 'json/**'

jobs:
  update-json-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits to compare

      - name: Check for file additions or deletions
        id: check_changes
        run: |
          echo "Checking for added or deleted files..."
          git diff --name-status HEAD^ HEAD

          if git rev-parse HEAD^ >/dev/null 2>&1; then
            added=$(git diff --name-status HEAD^ HEAD | grep '^A' | grep 'json/' | wc -l)
            deleted=$(git diff --name-status HEAD^ HEAD | grep '^D' | grep 'json/' | wc -l)
          else
            added=$(git ls-files --others --exclude-standard -- 'json/*' | wc -l)
            deleted=0
          fi

          echo "Files added: $added"
          echo "Files deleted: $deleted"
          echo $added == '1'
          echo $added == '0'

          echo "files_added=$added" >> $GITHUB_ENV
          echo "files_deleted=$deleted" >> $GITHUB_ENV

      - name: Generate JSON file if files were added or removed
        if: env.files_added != '0' || env.files_deleted != '0'
        run: |
          files=$(ls json | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "$files" > json_index.json

          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git add json_index.json
          git commit -m "Update JSON index"

      - name: Push changes
        if: env.files_added != '0' || env.files_deleted != '0'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
